-- MySQL Script generated by MySQL Workbench
-- Wed May  1 21:33:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nome` VARCHAR(25) NULL,
  `SobreNome` VARCHAR(25) NULL,
  `rua` VARCHAR(25) NULL,
  `bairro` VARCHAR(25) NULL,
  `numero` INT NULL,
  `cep` VARCHAR(25) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Editora` (
  `idEditora` INT NOT NULL,
  `Cidade` VARCHAR(25) NULL,
  PRIMARY KEY (`idEditora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`obra` (
  `Isbn` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `anoPublicado` YEAR(4) NULL,
  `Edição` VARCHAR(25) NULL,
  `classificação` VARCHAR(25) NULL,
  `idioma` VARCHAR(20) NULL,
  `Editora_idEditora` INT NOT NULL,
  PRIMARY KEY (`Isbn`, `Editora_idEditora`),
  INDEX `fk_obra_Editora1_idx` (`Editora_idEditora` ASC) ,
  CONSTRAINT `fk_obra_Editora1`
    FOREIGN KEY (`Editora_idEditora`)
    REFERENCES `mydb`.`Editora` (`idEditora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `idAutor` INT NOT NULL,
  `nome` VARCHAR(25) NULL,
  `Sobrenome` VARCHAR(25) NULL,
  `Nacionalidade` VARCHAR(25) NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
  `obra_Isbn` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`obra_Isbn`, `Usuario_idUsuario`),
  INDEX `fk_table1_Usuario1_idx` (`Usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_table1_obra`
    FOREIGN KEY (`obra_Isbn`)
    REFERENCES `mydb`.`obra` (`Isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table2` (
  `Autor_idAutor` INT NOT NULL,
  `obra_Isbn` INT NOT NULL,
  PRIMARY KEY (`Autor_idAutor`, `obra_Isbn`),
  INDEX `fk_table2_obra1_idx` (`obra_Isbn` ASC) ,
  CONSTRAINT `fk_table2_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `mydb`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table2_obra1`
    FOREIGN KEY (`obra_Isbn`)
    REFERENCES `mydb`.`obra` (`Isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `idTelefone` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `telefone` INT NULL,
  PRIMARY KEY (`idTelefone`, `Usuario_idUsuario`),
  INDEX `fk_Telefone_Usuario1_idx` (`Usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_Telefone_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
